server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.128:3306/personal
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.entity

logging:
  level:
    com:
      mapper: debug